name: "xray2airwaynan"
module_type: "basic_segmentation"
checkpoint_path: "checkpoints/xray2airwaynan.pth"
loadSize: 512
threshold: -1015
output_min_max: "-1100,-500"
calculate_area: true
calculate_volume: false
use_connected_regions: true
n_regions: 2
normalization_method: "percentile"
percentile_min: 0
percentile_max: 99
requires_lung_mask: false
interpolation: "LANCZOS"
