name: "xray2bone"
module_type: "basic_segmentation"
checkpoint_path: "checkpoints/xray2bone.pth"
loadSize: 2048
threshold: -1024
output_min_max: "-1100,-500"
calculate_area: true
calculate_volume: false
use_connected_regions: true
n_regions: 2
normalization_method: "percentile"
percentile_min: 0
percentile_max: 99
requires_lung_mask: false
interpolation: "LANCZOS"
