name: Build Windows Executables

on:
  push:
    branches: [ nuitka ]
  workflow_dispatch:  # Allows manual trigger from GitHub website

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-windows.txt
        pip install nuitka
    
    - name: Build inference.exe
      run: |
        echo Building inference.exe...
        python -m nuitka --standalone --assume-yes-for-downloads --output-dir=dist-inference --follow-imports inference.py
    
    - name: Build inference_ray.exe
      run: |
        echo Building inference_ray.exe...
        python -m nuitka --standalone --assume-yes-for-downloads --output-dir=dist-inference-ray --follow-imports inference_ray.py
    
    - name: Create distribution folder
      run: |
        mkdir dcx-windows
        xcopy dist-inference\inference.dist dcx-windows\inference\ /E /I
        xcopy dist-inference-ray\inference_ray.dist dcx-windows\inference_ray\ /E /I
        echo DCX Windows Build > dcx-windows\README.txt
        dir dcx-windows
    
    - name: Upload Windows executables
      uses: actions/upload-artifact@v4
      with:
        name: dcx-windows-executables
        path: dcx-windows/**