name: Build Windows Executable

on:
  push:
    branches: [ nuitka ]
  workflow_dispatch:  # Allows manual trigger from GitHub website

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
    
    - name: Build inference.exe with Nuitka
      run: |
        python -m nuitka --standalone --onefile --assume-yes-for-downloads --windows-disable-console --enable-plugin=numpy --include-data-dir=configs=configs --include-data-dir=src=src --output-dir=dist inference.py
    
    - name: Test executable exists
      run: |
        dir dist\
        echo "Build completed successfully!"
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: dcx-windows-exe
        path: dist/inference.exe