name: Build Windows Executable (Ray Version)

on:
  push:
    branches: [ nuitka ]
  workflow_dispatch:  # Allows manual trigger from GitHub website

jobs:
  build-inference-ray:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-windows.txt
        pip install nuitka
    
    - name: Build inference_ray.exe with optimizations
      run: |
        echo Building inference_ray.exe...
        python -m nuitka --standalone --assume-yes-for-downloads --jobs=4 --output-dir=dist-inference-ray --follow-imports inference_ray.py
    
    - name: Create distribution package
      run: |
        mkdir dcx-windows-ray
        xcopy dist-inference-ray\inference_ray.dist dcx-windows-ray\ /E /I
        echo DCX Windows Build (Ray Version) > dcx-windows-ray\README.txt
        echo. >> dcx-windows-ray\README.txt
        echo Usage: inference_ray.exe --input file.dcm --output_dir results --all_modules >> dcx-windows-ray\README.txt
        dir dcx-windows-ray
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: dcx-windows-ray-executable
        path: dcx-windows-ray/**