name: Build Windows Executable

on:
  push:
    branches: [ nuitka ]
  workflow_dispatch:  # Allows manual trigger from GitHub website

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 hours max to avoid timeout
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install build tools first
        pip install nuitka zstandard ordered-set
        # Install PyTorch with CUDA support for Windows builds
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
        # Install remaining dependencies (PyTorch excluded from requirements file)
        pip install -r requirements-windows.txt
    
    - name: Download model checkpoints (if needed)
      run: |
        # Create checkpoints directory if it doesn't exist
        if (!(Test-Path "checkpoints")) { New-Item -ItemType Directory -Path "checkpoints" }
        echo "Checkpoints directory ready"
    
    - name: Fix Python path for imports
      run: |
        echo "import sys" > path_fix.py
        echo "import os" >> path_fix.py
        echo "sys.path.append(os.path.join(os.path.dirname(__file__), 'core'))" >> path_fix.py
        echo "" >> path_fix.py
        Get-Content path_fix.py, inference.py | Out-File -FilePath inference_fixed.py -Encoding utf8
    
    - name: Build inference.exe with Nuitka
      run: |
        python -m nuitka --standalone --assume-yes-for-downloads --output-dir=dist --follow-imports --include-data-dir=configs=configs --include-data-dir=src=src inference_fixed.py
    
    - name: Test executable exists
      run: |
        dir dist\
        if (Test-Path "dist\inference_fixed.dist\inference_fixed.exe") {
          echo "✓ Build completed successfully!"
        } else {
          echo "✗ Build failed - executable not found"
          exit 1
        }
    
    - name: Create release package
      run: |
        # Create a clean distribution folder
        New-Item -ItemType Directory -Path "dcx-windows" -Force
        
        # Copy the executable and required folders
        Copy-Item "dist\inference_fixed.dist\*" "dcx-windows\" -Recurse
        Copy-Item "configs" "dcx-windows\" -Recurse -Force
        Copy-Item "README.md" "dcx-windows\" -Force
        
        # Create a simple batch file for easy execution
        echo "@echo off" > dcx-windows\run_dcx.bat
        echo "echo DCX Medical Imaging Inference - Windows Build" >> dcx-windows\run_dcx.bat
        echo "echo." >> dcx-windows\run_dcx.bat
        echo "echo Usage: inference_fixed.exe --module [module] --input_path [input] --output_dir [output]" >> dcx-windows\run_dcx.bat
        echo "echo." >> dcx-windows\run_dcx.bat
        echo "echo Available modules: lung, heart, airway, bone, covid, vessel, aorta, diameter, ctr, peripheral" >> dcx-windows\run_dcx.bat
        echo "echo." >> dcx-windows\run_dcx.bat
        echo "echo Example: inference_fixed.exe --module lung --input_path input.dcm --output_dir results" >> dcx-windows\run_dcx.bat
        echo "echo." >> dcx-windows\run_dcx.bat
        echo "pause" >> dcx-windows\run_dcx.bat
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: dcx-windows-executable
        path: dcx-windows/    
        retention-days: 30
    
    - name: Upload build logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          *.log
          dist/
        retention-days: 7