name: Build Windows Executable

on:
  push:
    branches: [ nuitka ]
  workflow_dispatch:  # Allows manual trigger from GitHub website

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-windows.txt
        pip install nuitka
    
    - name: Fix Python path for imports
      run: |
        echo "import sys; sys.path.append('core')" > path_fix.py
        type path_fix.py inference.py > inference_fixed.py
    
    - name: Build inference.exe with Nuitka
      run: |
        python -m nuitka --standalone --assume-yes-for-downloads --output-dir=dist --follow-imports inference_fixed.py
    
    - name: Test executable exists
      run: |
        dir dist\
        echo "Build completed successfully!"
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: dcx-windows-exe
        path: dist/inference_fixed.dist/*