name: "xray2airwaynan"
checkpoint_path: "checkpoints/xray2airwaynan.pth"
loadSize: 512
threshold: -1015
output_range: [-1000, -500]
calculate_area: true
use_connected_regions: true
n_regions: 1
normalization_method: "percentile"
percentile_min: 0
percentile_max: 99
requires_lung_mask: false