name: "heart_volumetry"
module_type: "volumetry"
checkpoint_path: "checkpoints/xray2heart.pth"
regression_checkpoint_path: "checkpoints/heartregression.pth"
loadSize: 512
threshold: -1015
output_range: [-1100, -500]
calculate_area: false
calculate_volume: true
use_connected_regions: false
normalization_method: "percentile"
percentile_min: 0
percentile_max: 99
requires_lung_mask: false
interpolation: "LANCZOS"
